# Generated by Django 6.0.6 on 2026-07-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.IntegerField(unique=True)),
                ('category', models.CharField(max_length=20)),
                ('clue', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('staus', models.CharField(max_length=5)),
            ],
        ),
    ]
