# Generated by Django 6.0.6 on 2026-07-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_number',
            field=models.IntegerField(),
        ),
    ]
