# Generated by Django 6.0.6 on 2026-07-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadmin', '0003_category_clue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='response',
            new_name='answer',
        ),
    ]
